language: node_js
node_js:
  - "10.15.3"
branches:
  only:
    - master
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt

before_install:
  - brew install yarn

install:
  - yarn install
  - yarn start

script:
  - yarn test-with-coverage
